using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Net;
using Microsoft.Extensions.Logging;


namespace Nike.Exceptions;

/// <summary>
///     Represents a exception that occurs during validation of input data of methods.
/// </summary>
public class ValidationException : GeneralException
{
    public const int ExceptionCode = 1;

    /// <summary>
    ///     Initializes a new instance of the ValidationException class using an error message generated by the system.
    /// </summary>
    /// <param name="message">The error message</param>
    /// <param name="validationErrors">
    ///     The list of <</param>
    public ValidationException(string message, IList<ValidationResult> validationErrors) : base(message, "",
        HttpStatusCode.BadRequest)
    {
        ValidationErrors = validationErrors ?? new List<ValidationResult>();
        ErrorCode = ExceptionCode;
        Level = LogLevel.Warning;
    }

    /// <summary>
    /// </summary>
    /// <param name="message">The error message</param>
    /// <param name="innerException">The underlying exception which caused this instance of ParooValidationException</param>
    public ValidationException(string message, Exception innerException = null) : base(message, "",
        innerException, HttpStatusCode.BadRequest)
    {
        ValidationErrors =  new List<ValidationResult>(){new(message)};
        ErrorCode = ExceptionCode;
        Level = LogLevel.Warning;
    }

    /// <summary>
    ///     Detailed list of validation errors for this exception.
    /// </summary>
    public IList<ValidationResult> ValidationErrors { get; protected set; } = new List<ValidationResult>();
}