name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./Nike.Api/Nike.Api.csproj
    - name: Build
      #run: dotnet build --configuration Release --no-restore ./Nike.Api/Nike.Api.csproj
      run: dotnet pack ./Nike.Api/Nike.Api.csproj  -c Release -o ./Nike.Api/nuget
      #run: dotnet test --no-restore --verbosity normal ./Nike.Api/Nike.Api.csproj
    - name: Deploy
      run: dotnet nuget push ./Nike.Api/nuget/Nike.Api*.nupkg  -k oy2fbqdpc2cwvanqy6kq5og4fpj2mcvexesndtrqul6axe -s https://api.nuget.org/v3/index.json
