name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.407'


    #- name: Install dependencies Nike.Api
    #  run: dotnet restore ./Nike.Api/Nike.Api.csproj
    #- name: Build Nike.Api
    #  run: dotnet pack ./Nike.Api/Nike.Api.csproj  -c Release -o ./nuget
    #- name: Install dependencies Nike.CustomerManagement.Tests.Units
    #  run: dotnet restore ./Nike.CustomerManagement.Tests.Units/Nike.CustomerManagement.Tests.Units.csproj
    #- name: Build Nike.CustomerManagement.Tests.Units
    #  run: dotnet pack ./Nike.CustomerManagement.Tests.Units/Nike.CustomerManagement.Tests.Units.csproj  -c Release -o ./nuget
    #- name: Install dependencies Nike.CustomerManagement
    #  run: dotnet restore ./Nike.CustomerManagement/Nike.CustomerManagement.csproj
    #- name: Build Nike.CustomerManagement
    #  run: dotnet pack ./Nike.CustomerManagement/Nike.CustomerManagement.csproj  -c Release -o ./nuget
    - name: Install dependencies Nike.EntityFramework.Microsoft.DependencyInjection
      run: dotnet restore ./Nike.EntityFramework.Microsoft.DependencyInjection/Nike.EntityFramework.Microsoft.DependencyInjection.csproj
    - name: Build Nike.EntityFramework.Microsoft.DependencyInjection
      run: dotnet pack ./Nike.EntityFramework.Microsoft.DependencyInjection/Nike.EntityFramework.Microsoft.DependencyInjection.csproj  -c Release -o ./nuget
    - name: Install dependencies Nike.EntityFramework
      run: dotnet restore ./Nike.EntityFramework/Nike.EntityFramework.csproj
    - name: Build Nike.EntityFramework
      run: dotnet pack ./Nike.EntityFramework/Nike.EntityFramework.csproj  -c Release -o ./nuget
    - name: Install dependencies Nike.EventBus.Kafka
      run: dotnet restore ./Nike.EventBus.Kafka/Nike.EventBus.Kafka.csproj
    - name: Build Nike.EventBus.Kafka
      run: dotnet pack ./Nike.EventBus.Kafka/Nike.EventBus.Kafka.csproj  -c Release -o ./nuget
    - name: Install dependencies Nike.EventBus.RabbitMQ
      run: dotnet restore ./Nike.EventBus.RabbitMQ/Nike.EventBus.RabbitMQ.csproj
    - name: Build Nike.EventBus.RabbitMQ
      run: dotnet pack ./Nike.EventBus.RabbitMQ/Nike.EventBus.RabbitMQ.csproj  -c Release -o ./nuget
    - name: Install dependencies Nike.EventBus
      run: dotnet restore ./Nike.EventBus/Nike.EventBus.csproj
    - name: Build Nike.EventBus
      #run: dotnet build --configuration Release --no-restore ./Nike.EventBus/Nike.EventBus.csproj
      run: dotnet pack ./Nike.EventBus/Nike.EventBus.csproj  -c Release -o ./nuget	  
    - name: Install dependencies Nike.Exceptions
      run: dotnet restore ./Nike.Exceptions/Nike.Exceptions.csproj
    - name: Build Nike.Exceptions
      run: dotnet pack ./Nike.Exceptions/Nike.Exceptions.csproj  -c Release -o ./nuget
    - name: Install dependencies Nike.Framework.Domain
      run: dotnet restore ./Nike.Framework.Domain/Nike.Framework.Domain.csproj
    - name: Build Nike.Framework.Domain
      run: dotnet pack ./Nike.Framework.Domain/Nike.Framework.Domain.csproj  -c Release -o ./nuget
    - name: Install dependencies Nike.Mediator
      run: dotnet restore ./Nike.Mediator/Nike.Mediator.csproj
    - name: Build Nike.Mediator
      run: dotnet pack ./Nike.Mediator/Nike.Mediator.csproj  -c Release -o ./nuget
    - name: Install dependencies  Nike.Redis.Microsoft.DependencyInjection
      run: dotnet restore ./Nike.Redis.Microsoft.DependencyInjection/Nike.Redis.Microsoft.DependencyInjection.csproj
    - name: Build Nike.Redis.Microsoft.DependencyInjection
      run: dotnet pack ./Nike.Redis.Microsoft.DependencyInjection/Nike.Redis.Microsoft.DependencyInjection.csproj  -c Release -o ./nuget
    - name: Install dependencies Nike.Swagger
      run: dotnet restore ./Nike.Swagger/Nike.Swagger.csproj
    - name: Build Nike.Swagger
      run: dotnet pack ./Nike.Swagger/Nike.Swagger.csproj  -c Release -o ./nuget
    - name: Install dependencies Nike.Web.DependencyInjection
      run: dotnet restore ./Nike.Web.DependencyInjection/Nike.Web.DependencyInjection.csproj
    - name: Build Nike.Web.DependencyInjection
      run: dotnet pack ./Nike.Web.DependencyInjection/Nike.Web.DependencyInjection.csproj  -c Release -o ./nuget
    - name: Install dependencies Nike.Web
      run: dotnet restore ./Nike.Web/Nike.Web.csproj
    - name: Build Nike.Web
      run: dotnet pack ./Nike.Web/Nike.Web.csproj  -c Release -o ./nuget
    - name: Install dependencies Nike.Logging
      run: dotnet restore ./Nike.Logging/Nike.Logging.csproj
    - name: Build Nike.Logging
      run: dotnet pack ./Nike.Logging/Nike.Logging.csproj  -c Release -o ./nuget
      
      
    - name: ls
      run: ls -lah ./nuget 
    - name: Deploy Nike.EntityFramework
      run: dotnet nuget push /home/runner/work/Nike/Nike/nuget/Nike.EntityFramework*.nupkg  -k oy2evwhaoguumse5phpqu3qwfnruteaudaw62fs62opvqm -s https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Deploy Nike.EntityFramework.Microsoft.DependencyInjection
      run: dotnet nuget push /home/runner/work/Nike/Nike/nuget/Nike.EntityFramework.Microsoft.DependencyInjection*.nupkg  -k oy2evwhaoguumse5phpqu3qwfnruteaudaw62fs62opvqm -s https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Deploy Nike.EventBus
      run: dotnet nuget push /home/runner/work/Nike/Nike/nuget/Nike.EventBus*.nupkg  -k oy2evwhaoguumse5phpqu3qwfnruteaudaw62fs62opvqm -s https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Deploy Nike.EventBus.Kafka
      run: dotnet nuget push /home/runner/work/Nike/Nike/nuget/Nike.EventBus.Kafka*.nupkg  -k oy2evwhaoguumse5phpqu3qwfnruteaudaw62fs62opvqm -s https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Deploy Nike.EventBus.RabbitMQ
      run: dotnet nuget push /home/runner/work/Nike/Nike/nuget/Nike.EventBus.RabbitMQ*.nupkg  -k oy2evwhaoguumse5phpqu3qwfnruteaudaw62fs62opvqm -s https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Deploy Nike.Exceptions
      run: dotnet nuget push /home/runner/work/Nike/Nike/nuget/Nike.Exceptions*.nupkg  -k oy2evwhaoguumse5phpqu3qwfnruteaudaw62fs62opvqm -s https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Deploy Nike.Framework.Domain
      run: dotnet nuget push /home/runner/work/Nike/Nike/nuget/Nike.Framework.Domain*.nupkg  -k oy2evwhaoguumse5phpqu3qwfnruteaudaw62fs62opvqm -s https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Deploy Nike.Mediator
      run: dotnet nuget push /home/runner/work/Nike/Nike/nuget/Nike.Mediator*.nupkg  -k oy2evwhaoguumse5phpqu3qwfnruteaudaw62fs62opvqm -s https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Deploy Nike.Redis.Microsoft.DependencyInjection
      run: dotnet nuget push /home/runner/work/Nike/Nike/nuget/Nike.Redis.Microsoft.DependencyInjection*.nupkg  -k oy2evwhaoguumse5phpqu3qwfnruteaudaw62fs62opvqm -s https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Deploy Nike.Swagger
      run: dotnet nuget push /home/runner/work/Nike/Nike/nuget/Nike.Swagger*.nupkg  -k oy2evwhaoguumse5phpqu3qwfnruteaudaw62fs62opvqm -s https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Deploy Nike.Web
      run: dotnet nuget push /home/runner/work/Nike/Nike/nuget/Nike.Web*.nupkg  -k oy2evwhaoguumse5phpqu3qwfnruteaudaw62fs62opvqm -s https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Deploy Nike.Web.DependencyInjection
      run: dotnet nuget push /home/runner/work/Nike/Nike/nuget/Nike.Web.DependencyInjection*.nupkg  -k oy2evwhaoguumse5phpqu3qwfnruteaudaw62fs62opvqm -s https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Deploy Nike.Logging
      run: dotnet nuget push /home/runner/work/Nike/Nike/nuget/Nike.Logging*.nupkg  -k oy2evwhaoguumse5phpqu3qwfnruteaudaw62fs62opvqm -s https://api.nuget.org/v3/index.json --skip-duplicate
      
